# Generated by Django 5.2.17 on 2026-08-18 15:38

import apps.events.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('rsvp_deadline', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64, validators=[apps.events.models.validate_iana_timezone])),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='events_event_name_not_empty'), models.CheckConstraint(condition=models.Q(('location', ''), _negated=True), name='events_event_location_not_empty'), models.CheckConstraint(condition=models.Q(('rsvp_deadline__lte', models.F('starts_at'))), name='events_event_rsvp_deadline_lte_starts_at'), models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'FINALIZED', 'CANCELLED'])), name='events_event_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='InvitationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_categories', to='events.event')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='events_invitation_category_name_not_empty'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('event'), name='events_invitation_category_event_name_ci_unique')],
            },
        ),
    ]
