# Generated by Django 5.2.17 on 2026-08-18 22:24

import django.db.models.deletion
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventmembership'),
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.UnaccentExtension(),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_check_ins', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_check_ins', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='guests.guest')),
            ],
            options={
                'ordering': ('-checked_in_at', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('guest',), name='checkins_one_active_per_guest'), models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), models.Q(('cancellation_reason__isnull', False), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='checkins_cancellation_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='CheckInOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('action', models.CharField(choices=[('INDIVIDUAL', 'Individual check-in'), ('GROUP', 'Group check-in'), ('CANCEL', 'Cancel check-in')], max_length=10)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_in_operations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_in_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'idempotency_key'), name='checkins_operation_event_user_key_unique'), models.CheckConstraint(condition=models.Q(models.Q(('response_payload__isnull', True), ('response_status__isnull', True)), models.Q(('response_payload__isnull', False), ('response_status__isnull', False)), _connector='OR'), name='checkins_operation_response_state_consistent')],
            },
        ),
    ]
