# Generated by Django 5.2.17 on 2026-08-18 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('responsible_name', models.CharField(max_length=255)),
                ('responsible_phone', models.CharField(blank=True, max_length=32)),
                ('guest_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invitations', to='events.invitationcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='invitations_invitation_description_not_empty'), models.CheckConstraint(condition=models.Q(('responsible_name', ''), _negated=True), name='invitations_invitation_responsible_name_not_empty'), models.CheckConstraint(condition=models.Q(('guest_limit__gte', 1)), name='invitations_invitation_guest_limit_gte_1')],
            },
        ),
    ]
