# Generated by Django 5.2.17 on 2026-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='public_token_issued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('public_token__isnull', True), models.Q(('public_token', ''), _negated=True), _connector='OR'), name='invitations_public_token_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('public_token__isnull', True), ('public_token_issued_at__isnull', True)), models.Q(('public_token__isnull', False), ('public_token_issued_at__isnull', False)), _connector='OR'), name='invitations_public_token_issued_state_valid'),
        ),
    ]
