# Generated by Django 5.2.17 on 2026-08-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_public_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined')], max_length=9)),
                ('guest_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='invitations.invitation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['CONFIRMED', 'DECLINED'])), name='invitations_response_status_valid')],
            },
        ),
    ]
